<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateAdminRoleTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('admin_role', function (Blueprint $table) {
            $table->increments('id');
            $table->string('name', 255)->comment('角色名称');
            $table->string('description', 255)->comment('角色描述');
            $table->integer('created_at');
            $table->integer('updated_at');
            $table->tinyInteger('is_on')->default(1);

            $table->unique('name', 'roles_name_unique');

            

        });

        DB::table('admin_role')->insert([
            'name' => '超级管理员',
            'description' => '超级管理员',
            'created_at' => time(),
            'updated_at' => time()
        ]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('admin_role');
    }
}
