<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateAdminUserTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('admin_user', function (Blueprint $table) {
            $table->increments('id');
            $table->string('account', 255)->comment('管理员登录账号');
            $table->string('password', 255)->comment('管理员登录密码');
            $table->string('salt', 255)->comment('组合密码加密用的扰乱串');
            $table->string('name', 255)->comment('管理员昵称');
            $table->string('headimg', 255)->nullable()->comment('头像');
            $table->bigInteger('last_login_ip')->comment('用户最后一次登录的ip');
            $table->integer('last_login_time')->comment('最后登录时间');
            $table->integer('created_at')->comment('创建时间');
            $table->integer('updated_at')->comment('更新时间');
            $table->integer('is_on')->default(1)->comment('管理员帐户状态。0为已删除，1为正常');

            

            

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('admin_user');
    }
}
