<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateAdminMenuTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('admin_menu', function (Blueprint $table) {
            $table->increments('id');
            $table->string('name', 255)->comment('菜单名称');
            $table->string('url', 255)->nullable();
            $table->string('icon', 255)->nullable()->comment('图标地址');
            $table->tinyInteger('level')->default(1)->comment('层级');
            $table->integer('parent_id')->comment('父级id');
            $table->integer('created_at');
            $table->integer('updated_at');
            $table->tinyInteger('is_on')->default(1);
            $table->integer('order')->comment('排序');
            $table->string('description', 255)->nullable()->comment('菜单描述');

            

            

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('admin_menu');
    }
}
