<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateUserAuthOauthTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('user_auth_oauth', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('user_id')->nullable();
            $table->tinyInteger('oauth_type')->nullable()->default(1)->comment('OAuth类型:1,微信;2,qq;3,微博;');
            $table->string('id1', 255)->comment('授权id:对应微信的openid');
            $table->string('id2', 255)->comment('授权id2:对应微信的unionid_id');
            $table->string('access_token', 255)->nullable();
            $table->integer('expires_time')->nullable();
            $table->string('info', 255)->nullable();
            $table->integer('created_at')->nullable();
            $table->integer('updated_at')->nullable();

            

            

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('user_auth_oauth');
    }
}
