<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateAdminPermissionTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('admin_permission', function (Blueprint $table) {
            $table->increments('id');
            $table->string('name', 255);
            $table->string('code', 255)->nullable()->comment('规则代码');
            $table->string('description', 255)->nullable()->comment('描述');
            $table->integer('parent_id')->comment('父级id');
            $table->tinyInteger('level')->default(2)->comment('层级，1级为组，2级为权限');
            $table->integer('created_at');
            $table->integer('updated_at');
            $table->unsignedTinyInteger('is_on')->default(1);

            

            

        });

        DB::table('admin_permission')->insert([
            'name' => '管理员管理权限',
            'description' => '管理员管理权限',
            'parent_id' => '0',
            'level' => '1',
            'created_at' => time(),
            'updated_at' => time()
        ]);

        DB::table('admin_permission')->insert([
            'name' => '角色管理权限组',
            'description' => '角色管理权限组',
            'parent_id' => '0',
            'level' => '1',
            'created_at' => time(),
            'updated_at' => time()
        ]);

        DB::table('admin_permission')->insert([
            'name' => '权限管理权限组',
            'description' => '权限管理权限组',
            'parent_id' => '0',
            'level' => '1',
            'created_at' => time(),
            'updated_at' => time()
        ]);

        DB::table('admin_permission')->insert([
            'name' => '菜单管理权限组',
            'description' => '菜单管理权限组',
            'parent_id' => '0',
            'level' => '1',
            'created_at' => time(),
            'updated_at' => time()
        ]);

        DB::table('admin_permission')->insert([
            'name' => '文章管理权限组',
            'description' => '文章管理权限组',
            'parent_id' => '0',
            'level' => '1',
            'created_at' => time(),
            'updated_at' => time()
        ]);

        DB::table('admin_permission')->insert([
            'name' => '文章分类权限组',
            'description' => '文章分类权限组',
            'parent_id' => '0',
            'level' => '1',
            'created_at' => time(),
            'updated_at' => time()
        ]);

        DB::table('admin_permission')->insert([
            'name' => '文章标签管理权限组',
            'description' => '文章标签管理权限组',
            'parent_id' => '0',
            'level' => '1',
            'created_at' => time(),
            'updated_at' => time()
        ]);

        DB::table('admin_permission')->insert([
            'name' => '管理员列表',
            'description' => '管理员列表',
            'code' => 'AdminUser@index',
            'parent_id' => '1',
            'level' => '2',
            'created_at' => time(),
            'updated_at' => time()
        ]);

        DB::table('admin_permission')->insert([
            'name' => '添加管理员',
            'description' => '添加管理员',
            'code' => 'AdminUser@store',
            'parent_id' => '1',
            'level' => '2',
            'created_at' => time(),
            'updated_at' => time()
        ]);

        DB::table('admin_permission')->insert([
            'name' => '编辑管理员',
            'description' => '编辑管理员',
            'code' => 'AdminUser@update',
            'parent_id' => '1',
            'level' => '2',
            'created_at' => time(),
            'updated_at' => time()
        ]);

        DB::table('admin_permission')->insert([
            'name' => '删除管理员',
            'description' => '删除管理员',
            'code' => 'AdminUser@destroy',
            'parent_id' => '1',
            'level' => '2',
            'created_at' => time(),
            'updated_at' => time()
        ]);

        DB::table('admin_permission')->insert([
            'name' => '角色列表',
            'description' => '角色列表',
            'code' => 'AdminRole@index',
            'parent_id' => '2',
            'level' => '2',
            'created_at' => time(),
            'updated_at' => time()
        ]);

        DB::table('admin_permission')->insert([
            'name' => '添加角色',
            'description' => '添加角色',
            'code' => 'AdminRole@store',
            'parent_id' => '2',
            'level' => '2',
            'created_at' => time(),
            'updated_at' => time()
        ]);

        DB::table('admin_permission')->insert([
            'name' => '编辑角色',
            'description' => '编辑角色',
            'code' => 'AdminRole@update',
            'parent_id' => '2',
            'level' => '2',
            'created_at' => time(),
            'updated_at' => time()
        ]);

        DB::table('admin_permission')->insert([
            'name' => '删除角色',
            'description' => '删除角色',
            'code' => 'AdminRole@destroy',
            'parent_id' => '2',
            'level' => '2',
            'created_at' => time(),
            'updated_at' => time()
        ]);

        DB::table('admin_permission')->insert([
            'name' => '修改角色权限',
            'description' => '修改角色权限',
            'code' => 'AdminRolePermission@update',
            'parent_id' => '2',
            'level' => '2',
            'created_at' => time(),
            'updated_at' => time()
        ]);

        DB::table('admin_permission')->insert([
            'name' => '查看角色权限',
            'description' => '查看角色权限',
            'code' => 'AdminRolePermission@index',
            'parent_id' => '2',
            'level' => '2',
            'created_at' => time(),
            'updated_at' => time()
        ]);

        DB::table('admin_permission')->insert([
            'name' => '权限列表',
            'description' => '权限列表',
            'code' => 'AdminPermission@index',
            'parent_id' => '3',
            'level' => '2',
            'created_at' => time(),
            'updated_at' => time()
        ]);

        DB::table('admin_permission')->insert([
            'name' => '添加权限',
            'description' => '添加权限',
            'code' => 'AdminPermission@store',
            'parent_id' => '3',
            'level' => '2',
            'created_at' => time(),
            'updated_at' => time()
        ]);

        DB::table('admin_permission')->insert([
            'name' => '编辑权限',
            'description' => '编辑权限',
            'code' => 'AdminPermission@update',
            'parent_id' => '3',
            'level' => '2',
            'created_at' => time(),
            'updated_at' => time()
        ]);

        DB::table('admin_permission')->insert([
            'name' => '删除权限',
            'description' => '删除权限',
            'code' => 'AdminPermission@destroy',
            'parent_id' => '3',
            'level' => '2',
            'created_at' => time(),
            'updated_at' => time()
        ]);

        DB::table('admin_permission')->insert([
            'name' => '查看权限菜单',
            'description' => '查看权限菜单',
            'code' => 'AdminPermissionMenu@index',
            'parent_id' => '3',
            'level' => '2',
            'created_at' => time(),
            'updated_at' => time()
        ]);

        DB::table('admin_permission')->insert([
            'name' => '修改权限菜单',
            'description' => '修改权限菜单',
            'code' => 'AdminPermissionMenu@update',
            'parent_id' => '3',
            'level' => '2',
            'created_at' => time(),
            'updated_at' => time()
        ]);

        DB::table('admin_permission')->insert([
            'name' => '菜单列表',
            'description' => '菜单列表',
            'code' => 'AdminMenu@index',
            'parent_id' => '4',
            'level' => '2',
            'created_at' => time(),
            'updated_at' => time()
        ]);

        DB::table('admin_permission')->insert([
            'name' => '添加菜单',
            'description' => '添加菜单',
            'code' => 'AdminMenu@store',
            'parent_id' => '4',
            'level' => '2',
            'created_at' => time(),
            'updated_at' => time()
        ]);

        DB::table('admin_permission')->insert([
            'name' => '编辑菜单',
            'description' => '编辑菜单',
            'code' => 'AdminMenu@update',
            'parent_id' => '4',
            'level' => '2',
            'created_at' => time(),
            'updated_at' => time()
        ]);

        DB::table('admin_permission')->insert([
            'name' => '删除菜单',
            'description' => '删除菜单',
            'code' => 'AdminMenu@destroy',
            'parent_id' => '4',
            'level' => '2',
            'created_at' => time(),
            'updated_at' => time()
        ]);

        DB::table('admin_permission')->insert([
            'name' => '文章列表',
            'description' => '文章列表',
            'code' => 'Article@index',
            'parent_id' => '5',
            'level' => '2',
            'created_at' => time(),
            'updated_at' => time()
        ]);

        DB::table('admin_permission')->insert([
            'name' => '添加文章',
            'description' => '添加文章',
            'code' => 'Article@store',
            'parent_id' => '5',
            'level' => '2',
            'created_at' => time(),
            'updated_at' => time()
        ]);

        DB::table('admin_permission')->insert([
            'name' => '编辑文章',
            'description' => '编辑文章',
            'code' => 'Article@update',
            'parent_id' => '5',
            'level' => '2',
            'created_at' => time(),
            'updated_at' => time()
        ]);

        DB::table('admin_permission')->insert([
            'name' => '删除文章',
            'description' => '删除文章',
            'code' => 'Article@destroy',
            'parent_id' => '5',
            'level' => '2',
            'created_at' => time(),
            'updated_at' => time()
        ]);

        DB::table('admin_permission')->insert([
            'name' => '文章分类列表',
            'description' => '文章分类列表',
            'code' => 'ArticleCategory@index',
            'parent_id' => '6',
            'level' => '2',
            'created_at' => time(),
            'updated_at' => time()
        ]);

        DB::table('admin_permission')->insert([
            'name' => '添加文章分类',
            'description' => '添加文章分类',
            'code' => 'ArticleCategory@store',
            'parent_id' => '6',
            'level' => '2',
            'created_at' => time(),
            'updated_at' => time()
        ]);

        DB::table('admin_permission')->insert([
            'name' => '编辑文章分类',
            'description' => '编辑文章分类',
            'code' => 'ArticleCategory@update',
            'parent_id' => '6',
            'level' => '2',
            'created_at' => time(),
            'updated_at' => time()
        ]);

        DB::table('admin_permission')->insert([
            'name' => '删除文章分类',
            'description' => '删除文章分类',
            'code' => 'ArticleCategory@destroy',
            'parent_id' => '6',
            'level' => '2',
            'created_at' => time(),
            'updated_at' => time()
        ]);

        DB::table('admin_permission')->insert([
            'name' => '文章标签列表',
            'description' => '文章标签列表',
            'code' => 'ArticleTag@index',
            'parent_id' => '7',
            'level' => '2',
            'created_at' => time(),
            'updated_at' => time()
        ]);

        DB::table('admin_permission')->insert([
            'name' => '添加文章标签',
            'description' => '添加文章标签',
            'code' => 'ArticleTag@store',
            'parent_id' => '7',
            'level' => '2',
            'created_at' => time(),
            'updated_at' => time()
        ]);

        DB::table('admin_permission')->insert([
            'name' => '编辑文章标签',
            'description' => '编辑文章标签',
            'code' => 'ArticleTag@update',
            'parent_id' => '7',
            'level' => '2',
            'created_at' => time(),
            'updated_at' => time()
        ]);

        DB::table('admin_permission')->insert([
            'name' => '删除文章标签',
            'description' => '删除文章标签',
            'code' => 'ArticleTag@destroy',
            'parent_id' => '7',
            'level' => '2',
            'created_at' => time(),
            'updated_at' => time()
        ]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('admin_permission');
    }
}
